#!/usr/bin/env bash


scripts/make-migrations
scripts/migrate

scripts/init-ai-workflow-instance

cd app
DJANGO_SUPERUSER_PASSWORD=password \
    h1st createsuperuser ../my-h1st-app-config.yml \
    --no-input --username username --email user@h1st.ai
