#!/usr/bin/env python3


from h1st.django.util.config import config_app
config_app('app', 'my-h1st-app-config.yml')

from ai.workflow import MyWorkflow
from ai.models.my_model import MyModel


print(MyWorkflow.objects.get_or_create(
        first_step=MyModel.objects.create())[0])
